[package]
name = "bitterlemon"
version = "0.2.1"
authors = ["Simon Harris <simon@pearfalse.com>"]
description = "An RLE-based encoder and decoder for bit streams."
license = "MIT"
repository = "https://github.com/pearfalse/bitterlemon"
categories = ["compression"]
keywords = ["rle", "bitstream", "pack"]

[dependencies]
arrayvec = ">= 0.3"

[dev-dependencies]
random = ">= 0.12"
